import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import graphqlClient from "../app/graphql/graphql.setup";
import "./globals.css";
import ApolloProviderWrapper from "@/utils/wrapper/ApolloProviderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
      </body>
    </html>
  );
}
